### ISSUE TITLE
Compilation error in test/support/mock_server/jenkins.ex

### ISSUE THREAD

**Issue by dflima** [GPrimola/jenkiexs#24]
After fixing #21, there's a compilation error in `test/support/mock_server/jenkins.ex`

```
== Compilation error in file test/support/mock_server/jenkins.ex ==
** (SyntaxError) test/support/mock_server/jenkins.ex:8: syntax error before: '->'
    (elixir) lib/kernel/parallel_compiler.ex:229: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
```

The code is as follows:

```elixir
  get "/api/json" do
    cond do
      is_nil(conn.params["tree"]) ->

      String.match?(conn.params["tree"], ~r/\Ajobs/) ->
        "jobs[name,description,fullName,displayName,fullDisplayName,inQueue,buildable,disabled,nextBuildNumber,property[parameterDefinitions[name,defaultParameterValue[value]]]]"
    end
  end
```

There's no code block after `is_nil(conn.params["tree"]) ->`

**Comment by dflima** [comment]
Fixed by 3c0868994def5acd2064c403ad4638d8936b0542
